# Generated by Django 4.2.6 on 2023-11-30 00:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.CharField(max_length=120)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message=None), django.core.validators.MaxValueValidator(100, message=None)])),
            ],
        ),
    ]
